FileUpload/Models/FileUploadContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace FileUpload.Models
{
    public class FileUploadContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public FileUploadContext() : base("name=FileUploadContext")
        {
        }
        public System.Data.Entity.DbSet<FileUpload.Models.FileUploadModel> fileUploadModel{ get; set; }

    }
}

FileUpload/Models/FileUploadModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace FileUpload.Models
{
    public class FileUploadModel
    {
        [Key]
        public int FileId { get; set; }
        public byte[] File { get; set; }
        [Display(Name = "File Name")]
        public string FileName { get; set; }
    }
}

FileUpload/Models/FileUploadVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
namespace FileUpload.Models
{
    public class FileUploadVm
    {
        [Key]
        public int key { get; set; }
        [DisplayName("Select File to Upload")]
        public HttpPostedFileBase File { get; set; }
        [Display(Name = "File Name")]
        [Required]
        public string FileName { get; set; }
    }
}

FileUpload/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FileUpload.Models;
using FileUpload.Business;
namespace FileUpload.Controllers
{
    public class FileUploadController : Controller
    {
        private FileUploadContext db = new FileUploadContext();
        // GET: FileUpload
        public ActionResult Index()
        {
            List<FileUploadModel> fileUp = db.fileUploadModel.ToList();
            return View(fileUp);
        }
        public ActionResult FileUploadProcess()
        {
            var model = new FileUploadVm();
            return View(model);
        }
        [HttpPost]
        public ActionResult FileUploadProcess(FileUploadVm model,FileUploadBusiness fileUploadBusiness)
        {
            fileUploadBusiness.UploadFile(model);
            return RedirectToAction("Index");
        }
        public FileContentResult FileDownload(int? id, FileUploadBusiness fileUploadBusiness)
        {
          var file=  fileUploadBusiness.SearchFile(id);
          return File(fileUploadBusiness.fileData(file), "text", fileUploadBusiness.fileName(file));
        }
    }
}

FileUpload/Views/FileUpload/FileUploadProcess.cshtml
@model FileUpload.Models.FileUploadVm
@{
    ViewBag.Title = "FileUploadProcess";
}

<h2>FileUploadProcess</h2>
@using (Html.BeginForm("FileUploadProcess", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data", @class = "container", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "cols-sm-2 control-label" })
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                @Html.TextBoxFor(model => model.File, new { type = "file", @class = "form-control" })
                @Html.ValidationMessageFor(x => x.File, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-success">Upload File</button>
}

FileUpload/Views/FileUpload/Index.cshtml
@model IEnumerable<FileUpload.Models.FileUploadModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Upload File", "FileUploadProcess")
</p>
<table class="table">
    <tr>
       
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
       
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        <td>
            @Html.ActionLink("Download", "FileDownload", new { id=item.FileId })
           
        </td>
    </tr>
}

</table>

FileUpload/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>